apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wp
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
